# Generated by Django 6.0.2 on 2026-03-06 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('caller_number', models.CharField(max_length=50, verbose_name='Caller Number')),
                ('callee_number', models.CharField(max_length=50, verbose_name='Callee Number')),
                ('direction', models.CharField(default='inbound', max_length=10, verbose_name='Direction')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('voicemail', 'Voicemail'), ('busy', 'Busy'), ('failed', 'Failed')], default='completed', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration Seconds')),
                ('agent_id', models.UUIDField(blank=True, null=True, verbose_name='Agent Id')),
                ('recording_url', models.URLField(blank=True, verbose_name='Recording Url')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'voip_calllog',
                'abstract': False,
            },
        ),
    ]
